[development]
address = "0.0.0.0"
port = 3000
secret_key = "8Xui8SN4mI+7egV/9dlfYYLGQJeEx4+DwmSQLwDVXJg="
log = "normal"
workers = 6

[staging]
address = "0.0.0.0"
port = 3000
log = "normal"

[production]
address = "0.0.0.0"
port = 3000
log = "critical"
