CREATE TABLE pages (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  user_id INTEGER NOT NULL,
  rank INTEGER NOT NULL DEFAULT 0,
  top_level BOOLEAN NOT NULL DEFAULT 0,
  removed BOOLEAN NOT NULL DEFAULT 0,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME ON UPDATE CURRENT_TIMESTAMP
);