CREATE TABLE posts (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER NOT NULL,
  modified DATETIME ON UPDATE CURRENT_TIMESTAMP,
  user_modified_id INTEGER,
  title TEXT NOT NULL,
  content TEXT NOT NULL
);